name:                inspire
version:             0.1.0.0
github:              "sdukhovni/inspire"
license:             MIT
author:              "Van Chung and Sam Dukhovni"
maintainer:          "inspire7@mit.edu"
copyright:           "2018 Van Chung and Sam Dukhovni"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Improved interactive fiction development toolkit
category:            Games, Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sdukhovni/inspire#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec

library:
  source-dirs: src

executables:
  inspire-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inspire

tests:
  inspire-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inspire
